export const contactsStorage = [
    {
        contactType: "person",
        emails: [
            {
                email: "noreply-challenge-total@agorize.com",
                id: "39",
                isPrimary: 0,
                label: "unknown",
            },
        ],
        id: "12",
        image: {
            uri: "content://com.android.contacts/contacts/12/photo",
        },
        imageAvailable: true,
        lookupKey: "1899i4389a6c08f0a0653",
        name: "noreply-challenge-total@agorize.com",
    },
    {
        contactType: "person",
        firstName: "Air",
        id: "88",
        imageAvailable: false,
        lastName: "Fabien",
        lookupKey: "1899i54581d638eed3b93",
        middleName: "Tension",
        name: "Air Tension Fabien",
        phoneNumbers: [
            {
            id: "433",
            isPrimary: 0,
            label: "mobile",
            number: "04 19 57 39",
            type: "2",
            },
        ],
    },
    {
      contactType: "person",
      firstName: "Alex",
      id: "103",
      imageAvailable: false,
      lastName: "C",
      lookupKey: "1899i76d94aa309360ddd.3789r103-293F31572B292D2D",
      middleName: "Bac",
      name: "Alex Bac C",
      phoneNumbers: [
        {
            id: "304",
            isPrimary: 0,
            label: "mobile",
            number: "06 24 22 45",
            type: "2",
        },
        {
            id: "510",
            isPrimary: 0,
            label: "mobile",
            number: "06242245",
            type: "2",
        },
      ],
    },
    {
      contactType: "person",
      firstName: "Alkazar",
      id: "115",
      imageAvailable: false,
      lookupKey: "1899i1471dbc489c8471e",
      name: "Alkazar",
      phoneNumbers: [
        {
            id: "450",
            isPrimary: 1,
            label: "other",
            number: "074424568",
            type: "7",
        },
      ],
    },
    {
      contactType: "person",
      firstName: "Allen",
      id: "143",
      imageAvailable: false,
      lastName: "Ayastou",
      lookupKey: "1899i6b8260f08e0691a0.3789r143-293F3F31432959294D4F4551",
      name: "Allen Ayastou",
      phoneNumbers: [
        {
            id: "56",
            isPrimary: 0,
            label: "mobile",
            number: "07 69 04 47",
            type: "2",
        },
        {
            id: "710",
            isPrimary: 0,
            label: "mobile",
            number: "07690447",
            type: "2",
        },
      ],
    }	,
        {
          contactType: "person",
          firstName: "Amina",
          id: "451",
          imageAvailable: false,
          lastName: "Sourire",
          lookupKey: "3176r442-29413943294D45514B394B31.3789r443-29413943294D45514B394B31",
          name: "Amina Sourire",
          phoneNumbers: [
            {
                id: "1979",
                isPrimary: 0,
                label: "home",
                number: "013",
                type: "1",
            },
            {
                id: "1476",
                isPrimary: 0,
                label: "mobile",
                number: "074113413",
                type: "2",
            },
            {
                id: "1482",
                isPrimary: 0,
                label: "mobile",
                number: "074113413",
                type: "2",
            },
          ],
        },
        {
            contactType: "person",
            firstName: "Ana",
            id: "118",
            imageAvailable: false,
            lastName: "Servis",
            lookupKey: "1899i526463940c7e49b5.3789r118-2943294D314B53394D",
            name: "Ana Servis",
            phoneNumbers: [
                {
                    id: "418",
                    isPrimary: 0,
                    label: "mobile",
                    number: "+33 7 58 04 33 47",
                    type: "2",
                },
                {
                    id: "585",
                    isPrimary: 0,
                    label: "mobile",
                    number: "+33758043347",
                    type: "2",
                },
          ],
        },
        {
          contactType: "person",
          firstName: "Anaelle",
          id: "538",
          imageAvailable: false,
          lookupKey: "3176r526-294329313F3F31.3789r527-294329313F3F31",
          name: "Anaelle",
          phoneNumbers: [
            {
              id: "1709",
              isPrimary: 0,
              label: "mobile",
              number: "062283280",
              type: "2",
            },
            {
              id: "1715",
              isPrimary: 0,
              label: "mobile",
              number: "062283280",
              type: "2",
            },
          ],
        },
        {
          contactType: "person",
          firstName: "Archi",
          id: "255",
          imageAvailable: false,
          lookupKey: "3176r248-294B2D3739.3789r250-294B2D3739",
          name: "Archi",
          phoneNumbers: [
            {
              id: "985",
              isPrimary: 0,
              label: "mobile",
              number: "062111145",
              type: "2",
            },
            {
              id: "993",
              isPrimary: 0,
              label: "mobile",
              number: "062111145",
              type: "2",
            },
          ],
        },
        {
          contactType: "person",
          firstName: "Archimède",
          id: "200",
          imageAvailable: false,
          lookupKey: "3176r196-294B2D373941312F31.3789r197-294B2D373941312F31",
          name: "Archimède",
          phoneNumbers: [
            {
              id: "846",
              isPrimary: 0,
              label: "mobile",
              number: "074183777",
              type: "2",
            },
            {
              id: "852",
              isPrimary: 0,
              label: "mobile",
              number: "074183777",
              type: "2",
            },
          ],
        },
        {
          contactType: "person",
          firstName: "Arielle♥️",
          id: "403",
          imageAvailable: false,
          lookupKey: "3176r366-294B39313F3F31.3789r396-294B39313F3F31",
          name: "Arielle♥️",
          phoneNumbers: [
            {
              id: "1352",
              isPrimary: 0,
              label: "home",
              number: "066190138",
              type: "1",
            },
            {
              id: "1362",
              isPrimary: 0,
              label: "home",
              number: "066190138",
              type: "1",
            },
          ],
        },
        {
          contactType: "person",
          firstName: "Athena",
          id: "129",
          imageAvailable: false,
          lookupKey: "1899i75a122c408bf42d0.3789r129-294F37314329",
          name: "Athena",
          phoneNumbers: [
            {
              id: "163",
              isPrimary: 0,
              label: "mobile",
              number: "02 14 00 48",
              type: "2",
            },
            {
              id: "640",
              isPrimary: 0,
              label: "mobile",
              number: "02140048",
              type: "2",
            },
          ],
        },
        {
          contactType: "person",
          firstName: "Aubierge",
          id: "251",
          imageAvailable: false,
          lookupKey: "1899i1673ea4108c7b010.3789r247-29512B39314B3531",
          name: "Aubierge",
          phoneNumbers: [
            {
              id: "385",
              isPrimary: 0,
              label: "mobile",
              number: "04 85 72 08",
              type: "2",
            },
            {
              id: "984",
              isPrimary: 0,
              label: "mobile",
              number: "04857208",
              type: "2",
            },
          ],
        },
        {
          contactType: "person",
          firstName: "Aure",
          id: "67",
          imageAvailable: false,
          lastName: "Taxi",
          lookupKey: "1899i66dd41aa8fd041af",
          name: "Aure Taxi",
          phoneNumbers: [
            {
              id: "324",
              isPrimary: 0,
              label: "mobile",
              number: "06 12 98 68",
              type: "2",
            },
          ],
        },
        {
          contactType: "person",
          firstName: "Bac",
          id: "134",
          imageAvailable: false,
          lastName: "Enchainement",
          lookupKey: "1899i7e2c009b8ebbe1cf.3789r134-2B292D31432D37293943314131434F",
          name: "Bac Enchainement",
          phoneNumbers: [
            {
              id: "76",
              isPrimary: 0,
              label: "mobile",
              number: "06 99 62 16",
              type: "2",
            },
            {
              id: "665",
              isPrimary: 0,
              label: "mobile",
              number: "06996216",
              type: "2",
            },
          ],
        },
        {
          contactType: "person",
          firstName: "Balance",
          id: "719",
          imageAvailable: false,
          lastName: "Enq",
          lookupKey: "1055r708-2B293F29432D31314349",
          name: "Balance Enq",
          phoneNumbers: [
            {
              id: "2157",
              isPrimary: 0,
              label: "unknown",
              number: "*137#",
              type: "102",
            },
          ],
        },
        {
          contactType: "person",
          firstName: "Barrious",
          id: "723",
          imageAvailable: false,
          lookupKey: "3176r467-2B294B4B3945514D",
          name: "Barrious",
          phoneNumbers: [
            {
              id: "1550",
              isPrimary: 0,
              label: "mobile",
              number: "077577821",
              type: "2",
            },
          ],
        },
        {
          contactType: "person",
          firstName: "Barrious",
          id: "477",
          imageAvailable: false,
          lookupKey: "3789r468-2B294B4B3945514D",
          name: "Barrious",
          phoneNumbers: [
            {
              id: "1556",
              isPrimary: 0,
              label: "mobile",
              number: "077577821",
              type: "2",
            },
          ],
        },
        {
          contactType: "person",
          firstName: "Belgique",
          id: "544",
          imageAvailable: false,
          lookupKey: "3176r532-2B313F3539495131",
          name: "Belgique",
          phoneNumbers: [
            {
              id: "1730",
              isPrimary: 0,
              label: "mobile",
              number: "077892632",
              type: "2",
            },
          ],
      }
]