export const experienceStorage = [
    {
        id:1,
        title:'Boit de nuit',
        date: '2 Mai à 13:26',
        description: "Pour l'horizontale, vous pouvez essayer de placer la FlatList horizontale dans le ListHeaderComponent de la FlatList verticale et voir ce qui se passe",
        avatarUri: require("../assets/avatar/img1.jpg"),
        note: 4,
        voter: 12,
        entreprise: 'Airtel Gabon',
        start: '12 juillet 2008',
        end: '23 Mars 2011',
        recommendation: true,
        adresse: 'Okala, Akanda / Gabon', 
    },
    {   
        id:2,
        title:'Plombier',
        date: '2 Mai à 13:26',
        description: "Pour l'horizontale, vous pouvez essayer de placer la FlatList horizontale dans le ListHeaderComponent de la FlatList verticale et voir ce qui se passe",
        avatarUri: require("../assets/avatar/img1.jpg"),
        note: 0,
        voter: 1,
        entreprise: 'Libertis',
        start: '12 juillet 2008',
        end: '09 Septembre 2013',
        recommendation: true,
        adresse: 'Okala, Akanda / Gabon', 
    },
    {   
        id:3,
        title:'Décoration',
        date: '2 Mai à 13:26',
        description: "Les gestes couramment utilisés sur les appareils dotés d'écrans tactiles comprennent les balayages et les casseroles. Ceux-ci permettent à l'utilisateur de faire défiler une liste d'éléments ou de parcourir des pages de contenu. Pour ceux-ci, consultez le composant ScrollView Core.",
        avatarUri: require("../assets/avatar/img1.jpg"),
        note: 1,
        voter: 1,
        entreprise: 'SETRAG',
        start: '12 juillet 2008',
        end: '09 Septembre 2013',
        recommendation: true,
        adresse: 'Nzeng-Ayong, Libreville / Gabon', 
    },
    {   
        id:4,
        title:'Restaurant',
        date: '2 Mai à 13:26',
        description: "Si le bouton de base ne convient pas à votre application, vous pouvez créer votre propre bouton à l'aide de l'un des composants tactiles fournis par React Native. Les composants «tactiles» offrent la possibilité de capturer les gestes de tapotement et peuvent afficher des commentaires lorsqu'un geste est reconnu. Ces composants ne fournissent pas de style par défaut, cependant, vous devrez donc faire un peu de travail pour les rendre bien dans votre application.",
        avatarUri: require("../assets/avatar/img1.jpg"),
        note: 5,
        voter: 11,
        entreprise: 'Total',
        start: '12 juillet 2008',
        end: '09 Septembre 2013',
        recommendation: true,
        adresse: 'Charbonnages, Libreville / Gabon', 
    },
    {   
        id:5,
        title:'Mecanicien',
        date: '2 Mai à 13:26',
        description: "Pour l'horizontale, vous pouvez essayer de placer la FlatList horizontale dans le ListHeaderComponent de la FlatList verticale et voir ce qui se passe",
        avatarUri: require("../assets/avatar/img1.jpg"),
        note: 3,
        voter: 11,
        entreprise: 'Gabon Telecom',
        start: '12 juillet 2008',
        end: '09 Septembre 2013',
        recommendation: true,
        adresse: 'Okala, Akanda / Gabon', 
    }
]
