export const raceList = [
    { "key": "CHAT SANS RACE (EUROPE)", "value": "CHAT SANS RACE (EUROPÉEN)", },
    { "key": "ABYSSIN", "value": "ABYSSIN", },
    { "key": "AMERICAN BOBTAIL", "value": "AMERICAN BOBTAIL", },
    { "key": "AMERICAN CURL", "value": "AMERICAN CURL", },
    { "key": "AMERICAN SHORTHAIR", "value": "AMERICAN SHORTHAIR", },
    { "key": "AMERICAN WIREHAIR", "value": "AMERICAN WIREHAIR", },
    { "key": "ANATOLI (TURKISH SHORTHAIR)", "value": "ANATOLI (TURKISH SHORTHAIR)", },
    { "key": "ANGORA TURC", "value": "ANGORA TURC", },
    { "key": "ASIAN", "value": "ASIAN", },
    { "key": "AUSTRALIAN MIST", "value": "AUSTRALIAN MIST", },
    { "key": "BALINAIS", "value": "BALINAIS", },
    { "key": "BENGAL", "value": "BENGAL", },
    { "key": "BOMBAY", "value": "BOMBAY", },
    { "key": "BRAZILIAN SHORTHAIR", "value": "BRAZILIAN SHORTHAIR", },
    { "key": "BRITISH LONGHAIR", "value": "BRITISH LONGHAIR", },
    { "key": "BRITISH SHORTHAIR", "value": "BRITISH SHORTHAIR", },
    { "key": "BURMESE AMERICAIN", "value": "BURMESE AMERICAIN", },
    { "key": "BURMESE ANGLAIS", "value": "BURMESE ANGLAIS", },
    { "key": "BURMILLA", "value": "BURMILLA", },
    { "key": "CALIFORNIAN REX", "value": "CALIFORNIAN REX", },
    { "key": "CALIFORNIAN SPANGLED", "value": "CALIFORNIAN SPANGLED", },
    { "key": "CEYLAN", "value": "CEYLAN", },
    { "key": "CHANTILLY", "value": "CHANTILLY", },
    { "key": "CHARTREUX", "value": "CHARTREUX", },
    { "key": "CHAUSIE", "value": "CHAUSIE", },
    { "key": "COLORPOINT SHORTHAIR", "value": "COLORPOINT SHORTHAIR", },
    { "key": "CORNISH REX", "value": "CORNISH REX", },
    { "key": "CYMRIC", "value": "CYMRIC", },
    { "key": "DEVON REX", "value": "DEVON REX", },
    { "key": "DONSKOY", "value": "DONSKOY", },
    { "key": "EUROPEAN SHORTHAIR", "value": "EUROPEAN SHORTHAIR", },
    { "key": "EXOTIC SHORTHAIR", "value": "EXOTIC SHORTHAIR", },
    { "key": "GERMAN REX", "value": "GERMAN REX", },
    { "key": "HAVANA BROWN", "value": "HAVANA BROWN", },
    { "key": "HIMALAYEN", "value": "HIMALAYEN", },
    { "key": "JAPANESE BOBTAIL (BOBTAIL JAPONAIS)", "value": "JAPANESE BOBTAIL (BOBTAIL JAPONAIS)", },
    { "key": "KHAO MANEE", "value": "KHAO MANEE", },
    { "key": "KORAT", "value": "KORAT", },
    { "key": "LAPERM", "value": "LAPERM", },
    { "key": "LYKOI", "value": "LYKOI", },
    { "key": "MAINE COON", "value": "MAINE COON", },
    { "key": "MANDARIN", "value": "MANDARIN", },
    { "key": "MANX", "value": "MANX", },
    { "key": "MAU ARABE", "value": "MAU ARABE", },
    { "key": "MAU EGYPTIEN", "value": "MAU EGYPTIEN", },
    { "key": "MINSKIN", "value": "MINSKIN", },
    { "key": "MUNCHKIN", "value": "MUNCHKIN", },
    { "key": "NEBELUNG", "value": "NEBELUNG", },
    { "key": "NORVEGIEN OU SKOGKATT", "value": "NORVEGIEN OU SKOGKATT", },
    { "key": "OCICAT", "value": "OCICAT", },
    { "key": "OJOS AZULES", "value": "OJOS AZULES", },
    { "key": "ORIENTAL", "value": "ORIENTAL", },
    { "key": "PERSAN", "value": "PERSAN", },
    { "key": "PETERBALD", "value": "PETERBALD", },
    { "key": "PIXIE BOB", "value": "PIXIE BOB", },
    { "key": "RUSSE (OU BLEU RUSSE)", "value": "RUSSE (OU BLEU RUSSE)", },
    { "key": "SACRE DE BIRMANIE", "value": "SACRE DE BIRMANIE", },
    { "key": "SAFARI", "value": "SAFARI", },
    { "key": "SAVANNAH", "value": "SAVANNAH", },
    { "key": "SCOTTISH", "value": "SCOTTISH", },
    { "key": "SELKIRK REX", "value": "SELKIRK REX", },
    { "key": "SERENGETI", "value": "SERENGETI", },
    { "key": "SEYCHELLOIS", "value": "SEYCHELLOIS", },
    { "key": "SIAMOIS", "value": "SIAMOIS", },
    { "key": "SIBERIEN", "value": "SIBERIEN", },
    { "key": "SINGAPURA", "value": "SINGAPURA", },
    { "key": "SKOOKUM", "value": "SKOOKUM", },
    { "key": "SNOWSHOE", "value": "SNOWSHOE", },
    { "key": "SOKOKE", "value": "SOKOKE", },
    { "key": "SOMALI", "value": "SOMALI", },
    { "key": "SPHYNX", "value": "SPHYNX", },
    { "key": "THAI", "value": "THAI", },
    { "key": "TIFFANY", "value": "TIFFANY", },
    { "key": "TONKINOIS", "value": "TONKINOIS", },
    { "key": "TOYGER", "value": "TOYGER", },
    { "key": "TURC DU LAC DE VAN", "value": "TURC DU LAC DE VAN", },
    { "key": "URAL REX", "value": "URAL REX", },
    { "key": "YORK CHOCOLAT", "value": "YORK CHOCOLAT" }
]
